apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
  name: azure-kvname-msi # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: ""
    objects: |
      array:
        - |
          objectName: GITHUB-APP-ID
          objectType: secret
        - |
          objectName: GITHUB-APP-REG-ID
          objectType: secret
        - |
          objectName: GITHUB-APP-PVT
          objectType: secret
        - |
          objectName: azureserviceprincipal
          objectType: secret
        - |
          objectName: sample-weatherapi-dev-appinsights-connectionstring
          objectType: secret
        - |
          objectName: sample-weatherapi-dev-forecastapi-authtoken
          objectType: secret
        - |
          objectName: sample-weatherapi-dev-forecastsummary-authtoken
          objectType: secret
        - |
          objectName: sample-weatherapi-dev-weatherapi-authtoken
          objectType: secret
    tenantId: ""
  # Read https://samcogan.com/creating-kubernetes-secrets-from-azure-key-vault-with-the-csi-driver/ for details on why this is necessary. 
  secretObjects:
  - secretName: sample-weatherapi-secrets
    data:
    - key: sample-weatherapi-dev-appinsights-connectionstring
      objectName: sample-weatherapi-dev-appinsights-connectionstring
    - key: sample-weatherapi-dev-forecastapi-authtoken
      objectName: sample-weatherapi-dev-forecastapi-authtoken
    - key: sample-weatherapi-dev-forecastsummary-authtoken
      objectName: sample-weatherapi-dev-forecastsummary-authtoken
    - key: sample-weatherapi-dev-weatherapi-authtoken
      objectName: sample-weatherapi-dev-weatherapi-authtoken
    type: Opaque
