apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yodasbootst
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  project: default
  source:
    path: products/sample/apps/weatherApi/
    repoURL: https://github.com/it2008018/argoAppsetonAkuity
    directory:
      recurse: true
  syncPolicy:
    automated: {}
